### ISSUE TITLE
bugFix#1

### ISSUE THREAD

**Issue by WCSIsabelle** [WildCodeSchool/orleans-0217-myorleans#30]
- formulaire simple ne fonctionne pas quand un parcours est sélectionné --> besoin de fermer le form avec balise form
- remplacement du type d'image à afficher dans la plupart des vues : "image" -> "image-cover"

**Comment by open-it** [comment]
ce bug est il corrigé ? si oui on le clos.

**Comment by WCSIsabelle** [comment]
@open-it : oui c'est réglé, tu peux fermer l'issue! Thx
